name: Test & Deploy
on:
  push:
    paths:
      - "app/**/*"
defaults:
  run:
    working-directory: ./app
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - name: Install dependencies
        run: npm ci
      # - name: LINTing
        # run: npm run lint -- --quiet -f codeframe
      # - name: Prettier
        # run: npm run format -- --check
  # build:
    # runs-on: ubuntu-latest
    # needs: [test]
    # steps:
      # - uses: actions/checkout@v1
      # - uses: actions/setup-node@v1
        # with:
          # node-version: "12"
      # - name: Cache node modules
        # uses: actions/cache@v1
        # with:
          # path: node_modules
          # key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          # restore-keys: |
            # ${{ runner.OS }}-build-${{ env.cache-name }}-
            # ${{ runner.OS }}-build-
            # ${{ runner.OS }}-
      # - name: npm install and build
        # run: |
          # npm ci
          # npm run build-client --if-present
        # env:
          # CI: "true"
  s2i-build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [test]
    # needs: [test, build]
    steps:
      - name: S2I Build
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL}}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
            'start-build mals-app-dev --follow -n 30245e-tools'